package com.colearn.unsplashtask.pojos

import android.os.Parcel
import android.os.Parcelable
import com.google.gson.annotations.Expose
import com.google.gson.annotations.SerializedName

/*
*  Generated by https://www.jsonschema2pojo.org/
*/
class Links : Parcelable {
    @SerializedName("self")
    @Expose
    var self: String? = null

    @SerializedName("html")
    @Expose
    var html: String? = null

    @SerializedName("download")
    @Expose
    var download: String? = null

    @SerializedName("download_location")
    @Expose
    var downloadLocation: String? = null

    protected constructor(`in`: Parcel) {
        self = `in`.readValue(String::class.java.classLoader) as String?
        html = `in`.readValue(String::class.java.classLoader) as String?
        download = `in`.readValue(String::class.java.classLoader) as String?
        downloadLocation = `in`.readValue(String::class.java.classLoader) as String?
    }

    constructor() {}

    override fun writeToParcel(dest: Parcel, flags: Int) {
        dest.writeValue(self)
        dest.writeValue(html)
        dest.writeValue(download)
        dest.writeValue(downloadLocation)
    }

    override fun describeContents(): Int {
        return 0
    }

    companion object {
        val CREATOR: Parcelable.Creator<Links?> = object : Parcelable.Creator<Links?> {
            override fun createFromParcel(`in`: Parcel): Links? {
                return Links(`in`)
            }

            override fun newArray(size: Int): Array<Links?> {
                return arrayOfNulls(size)
            }
        }
    }
}