package com.colearn.unsplashtask.pojos

import com.google.gson.annotations.SerializedName
import java.util.*

/*
 *  Generated by https://www.jsonschema2pojo.org/
 */
class SearchResult {
    @SerializedName("total")
    var total: Int? = null

    @SerializedName("total_pages")
    var totalPages: Int? = null

    @SerializedName("results")
    var results: ArrayList<Photo>? = null
}