package com.colearn.unsplashtask.pojos

import android.os.Parcel
import android.os.Parcelable
import com.google.gson.annotations.Expose
import com.google.gson.annotations.SerializedName

/*
 *  Generated by https://www.jsonschema2pojo.org/
 */
class Urls : Parcelable {
    @SerializedName("raw")
    @Expose
    var raw: String? = null

    @SerializedName("full")
    @Expose
    var full: String? = null

    @SerializedName("regular")
    @Expose
    var regular: String? = null

    @SerializedName("small")
    @Expose
    var small: String? = null

    @SerializedName("thumb")
    @Expose
    var thumb: String? = null

    protected constructor(`in`: Parcel) {
        raw = `in`.readValue(String::class.java.classLoader) as String?
        full = `in`.readValue(String::class.java.classLoader) as String?
        regular = `in`.readValue(String::class.java.classLoader) as String?
        small = `in`.readValue(String::class.java.classLoader) as String?
        thumb = `in`.readValue(String::class.java.classLoader) as String?
    }

    constructor() {}

    override fun writeToParcel(dest: Parcel, flags: Int) {
        dest.writeValue(raw)
        dest.writeValue(full)
        dest.writeValue(regular)
        dest.writeValue(small)
        dest.writeValue(thumb)
    }

    override fun describeContents(): Int {
        return 0
    }

    companion object {
        val CREATOR: Parcelable.Creator<Urls?> = object : Parcelable.Creator<Urls?> {
            override fun createFromParcel(`in`: Parcel): Urls? {
                return Urls(`in`)
            }

            override fun newArray(size: Int): Array<Urls?> {
                return arrayOfNulls(size)
            }
        }
    }
}