package com.colearn.unsplashtask.pojos

import android.os.Parcel
import android.os.Parcelable
import com.google.gson.annotations.Expose
import com.google.gson.annotations.SerializedName

/*
 *  Generated by https://www.jsonschema2pojo.org/
 */
class UserLinks : Parcelable {
    @SerializedName("self")
    @Expose
    var self: String? = null

    @SerializedName("html")
    @Expose
    var html: String? = null

    @SerializedName("photos")
    @Expose
    var photos: String? = null

    @SerializedName("likes")
    @Expose
    var likes: String? = null

    @SerializedName("portfolio")
    @Expose
    var portfolio: String? = null

    protected constructor(`in`: Parcel) {
        self = `in`.readValue(String::class.java.classLoader) as String?
        html = `in`.readValue(String::class.java.classLoader) as String?
        photos = `in`.readValue(String::class.java.classLoader) as String?
        likes = `in`.readValue(String::class.java.classLoader) as String?
        portfolio = `in`.readValue(String::class.java.classLoader) as String?
    }

    constructor() {}

    override fun writeToParcel(dest: Parcel, flags: Int) {
        dest.writeValue(self)
        dest.writeValue(html)
        dest.writeValue(photos)
        dest.writeValue(likes)
        dest.writeValue(portfolio)
    }

    override fun describeContents(): Int {
        return 0
    }

    companion object {
        val CREATOR: Parcelable.Creator<UserLinks?> = object : Parcelable.Creator<UserLinks?> {
            override fun createFromParcel(`in`: Parcel): UserLinks? {
                return UserLinks(`in`)
            }

            override fun newArray(size: Int): Array<UserLinks?> {
                return arrayOfNulls(size)
            }
        }
    }
}